language: python

python:
    - "3.4"

sudo: false

install:


before_script:
    - uname -a
    - printenv
    - pip3 list

script:
    - date
    - ls -lah

after_success: |
    if [ "$TRAVIS_BRANCH" != "dev" ]; then
        exit 0;
    fi

    # Merge dev to beta
    if [ -n "$GITHUB_KEY" ]; then

        export GIT_COMMITTER_EMAIL=travis
        export GIT_COMMITTER_NAME=travis

        git fetch --all
        git branch -v -a
        git checkout beta || exit
        git merge "$TRAVIS_COMMIT" || exit
        git push https://mecca-ci:$GITHUB_KEY@github.com/naughtyfiddle/music-mecca.git
    fi
