notifications:
    email: false
    slack: musicmecca:V9OTfTGBTJXHwDY2DNKUVc7Y

language: python

python:
    - "3.4"

sudo: false

install:


before_script:
    - uname -a
    - printenv
    - pip3 list

script:
    - export CONFIG_PATH=/home/travis/build/naughtyfiddle/cs373-idb/config.py
    - nosetests tests/
    - date
    - ls -lah

after_success: |
    if [ "$TRAVIS_BRANCH" != "dev" ]; then
        exit 0;
    fi

    # Merge dev to beta
    if [ -n "$GITHUB_KEY" ]; then

        export GIT_COMMITTER_EMAIL=travis
        export GIT_COMMITTER_NAME=travis

        git clone https://mecca-ci:$GITHUB_KEY@github.com/naughtyfiddle/music-mecca.git merge
        cd merge
        git checkout beta || exit
        git merge origin/dev || exit
        git push https://mecca-ci:$GITHUB_KEY@github.com/naughtyfiddle/music-mecca.git
    fi
