FORMAT: 1A
HOST: http://downing.club/

# Music-Mecca API

Music Mecca is a source for information about musicians and bands, as well as the music they release.

# Group Artists

Artists are all musicians stored in our database. That includes solo artists or bands. 

## Artist Collection [/artists]

+ Model (application/json)

    + Body

            {
                "count": 2,
                "results": [
                    {
                        "id": 1,
                        "name": "Taylor Swift",
                        "bio": "Taylor Swift bio",
                        "photo": Raw photo data,
                        "videos": [
                            {
                                "id": 1,
                                "name": "Too Cool For School",
                                "year": "1989"
                            }
                        ],
                        "label": {
                            "id": 1,
                            "name": "Big Machine Records",
                            "bio": "Bio goes here"
                        },
                        "awards": [
                            {
                                "id": 1,
                                "name": "Album of the Year",
                                "year": "2015"
                            },
                            {
                                "id": 2,
                                "name": "Billboard Top 40",
                                "year": "2006"
                            }
                        ],
                        "concerts": [
                            {
                                "id": 1,
                                "name": "1989 Tour",
                                "location": "Austin",
                                "date": "2015-07-04 13:00:00-00"
                            },
                            {
                                "id": 2,
                                "name": "Warp Tour",
                                "location": "Alton",
                                "date": "2015-31-04 16:00:00-00"
                            }
                        ],
                        "releases": [
                            {
                                "id": 1,
                                "name": "Too Cool For School",
                                "year": "1989"
                            },
                            {
                                "id": 2,
                                "name": "Just Dance",
                                "year": "2010"
                            }
                        ]


                    },
                    {
                        "id": 2,
                        "name": "Eminem",
                        "bio": "Eminem bio",
                        "photo": Raw photo data,
                        "videos": [
                            {
                                "id": 2,
                                "name": "Mockingbird",
                                "year": "1998"
                            }
                        ],
                        "label": {
                            "id": 2,
                            "name": "Slim Shady Records",
                            "bio": "Bio goes here"
                        },
                        "awards": [
                            {
                                "id": 3,
                                "name": "Album of the Year",
                                "year": "2012"
                            },
                            {
                                "id": 4,
                                "name": "Billboard Top 40",
                                "year": "2008"
                            }
                        ],
                        "concerts": [
                            {
                                "id": 3,
                                "name": "1989 Tour",
                                "location": "Austin",
                                "date": "2015-07-04 13:00:00-00"
                            },
                            {
                                "id": 4,
                                "name": "Warp Tour",
                                "location": "Alton",
                                "date": "2015-31-04 16:00:00-00"
                            }
                        ],
                        "releases": [
                            {
                                "id": 3,
                                "name": "Curtain Call",
                                "year": "1989"
                            },
                            {
                                "id": 4,
                                "name": "Relapse",
                                "year": "2010"
                            }
                        ]


                    }
                ]
            }

### List All Artists [GET]

+ Response 200

    [Artist Collection][]


## Artist [/artist/{artistId}]

+ Model (application/json)
    + Headers
      Location: http://downing.club/artist/2

      + Body
            {
                "id": 2,
                "name": "Eminem",
                "bio": "Eminem bio",
                "photo": Raw photo data,
                "videos": [
                    {
                        "id": 2,
                        "name": "Mockingbird",
                        "year": "1998"
                    }
                ],
                "label": {
                    "id": 2,
                    "name": "Slim Shady Records",
                    "bio": "Bio goes here"
                },
                "awards": [
                    {
                        "id": 3,
                        "name": "Album of the Year",
                        "year": "2012"
                    },
                    {
                        "id": 4,
                        "name": "Billboard Top 40",
                        "year": "2008"
                    }
                ],
                "concerts": [
                    {
                        "id": 3,
                        "name": "1989 Tour",
                        "location": "Austin",
                        "date": "2015-07-04 13:00:00-00"
                    },
                    {
                        "id": 4,
                        "name": "Warp Tour",
                        "location": "Alton",
                        "date": "2015-31-04 16:00:00-00"
                    }
                ],
                "releases": [
                    {
                        "id": 3,
                        "name": "Curtain Call",
                        "year": "1989"
                    },
                    {
                        "id": 4,
                        "name": "Relapse",
                        "year": "2010"
                    }
                ]
            }

### Get an Aritist
+ Parameters
    + artistId (id) - ID of the song in the form of an integer

+ Response 200
[Artist][]

## Song [/song/{song_id}]
    + song_id (number) - ID of the song in the form of an integer

### View Song Info [GET]

+ Response 200 (application/json)


        {
            "id": 0001
            "name": "Bad Blood"
            "lyrics": "Lyrics go here"
            "artist": [00001, 00002]
            "release": [00001, 000004]
        }

## Award [/award/{award_id}]
    + award_id (number) - ID of the award in the form of an integer

### View Award Info [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "Album of the Year"
            "year": "2015"
            "artist" : [00001]
        }

## Label [/label/{label_id}]
    + label_id (number) - ID of the label in the form of an integer

### View Label Info [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "Big Machine Records"
            "bio": "Bio goes here"
            "artist": [00001, 00003, 00005]
        }

## Release [/release/{release_id}]
    + release_id (number) - ID of the release in the form of an integer

### View Release Info [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "1989"
            "artist": [00001]
        }

## Concert [/concert/{concert_id}]
    + concert_id (number) - ID of the concert in the form of an integer

### View Concert Info [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "1989 Tour"
            "location": "Austin"
            "date": "2015-07-04 13:00:00-00"
            "artist": [00001]
        }

