FORMAT: 1A
HOST: http://downing.club/

# Music-Mecca API

Music Mecca is a source for information about musicians and bands, as well as the music they release.

## Artist Collection [/artists]

### List All Artists [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

## Song [/song/{song_id}]
    + song_id (number) - ID of the song in the form of an integer

### View Song Info [GET]

+ Response 200 (application/json)


        {
            "id": 0001
            "name": "Bad Blood"
            "lyrics": "Lyrics go here"
            "artist": [00001, 00002]
            "release": [00001, 000004]
        }

## Award [/award/{award_id}]
    + award_id (number) - ID of the award in the form of an integer

### View Award Info [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "Album of the Year"
            "year": "2015"
            "artist" : [00001]
        }

## Label [/label/{label_id}]
    + label_id (number) - ID of the label in the form of an integer

### View Label Info [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "Big Machine Records"
            "bio": "Bio goes here"
            "photo": raw photo data
            "artist": [00001, 00003, 00005]
        }

## Release [/release/{release_id}]
    + release_id - ID of the release in the form of an integer

### View Release Info [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "1989"
            "artist": [00001]
        }