FORMAT: 1A
HOST: http://downing.club/

# Music-Mecca API

Music Mecca is a source for information about musicians and bands, as well as the music they release.

## Artist Collection [/artists]

### List All Artists [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

## Artist ID [/artist/{artist_id}]
    + artist_id (number) - ID of the artist in the form of an integer

### View Artist Info by ID [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "Taylor Swift"
            "bio": "Taylor Swift bio"
            "photo": Raw photo data
            "videos": [00001]
            "label": 00001
            "awards": [00001]
            "concerts": [00001]
            "releases": [00001]
            "songs": [00001]
        }

## Artist Name [/artist/{artist_name}]
    + artist_name (string) - name of the artist in the form of a string (spaces must be replaced by underscores)

### View Artist Info by Name [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "Taylor Swift"
            "bio": "Taylor Swift bio"
            "photo": Raw photo data
            "videos": [00001]
            "label": 00001
            "awards": [00001]
            "concerts": [00001]
            "releases": [00001]
            "songs": [00001]
        }

## Song ID [/song/{song_id}]
    + song_id (number) - ID of the song in the form of an integer

### View Song Info by ID [GET]

+ Response 200 (application/json)


        {
            "id": 0001
            "name": "Bad Blood"
            "lyrics": "Lyrics go here"
            "artist": [00001, 00002]
            "release": [00001, 000004]
        }
        
## Song Name [/song/{song_name}]
    + song_name (string) - name of the song in the form of a string (spaces must be underscores)

### View Song Info by Name [GET]

+ Response 200 (application/json)


        {
            "id": 0001
            "name": "Bad Blood"
            "lyrics": "Lyrics go here"
            "artist": [00001, 00002]
            "release": [00001, 000004]
        }

## Award ID [/award/{award_id}]
    + award_id (number) - ID of the award in the form of an integer

### View Award Info by ID [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "Album of the Year"
            "year": "2015"
            "artist" : [00001]
        }
        
## Award Name [/award/{award_name}]
    + award_name (string) - name of the award in the form of a string (spaces must be underscores)

### View Award Info by Name [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "Album of the Year"
            "year": "2015"
            "artist" : [00001]
        }

## Label ID [/label/{label_id}]
    + label_id (number) - ID of the label in the form of an integer

### View Label Info by ID [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "Big Machine Records"
            "bio": "Bio goes here"
            "photo": raw photo data
            "artist": [00001, 00003, 00005]
        }
        
## Label Name [/label/{label_name}]
    + label_name (string) - name of the label in the form of a string (spaces must be underscores)

### View Label Info by Name [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "Big Machine Records"
            "bio": "Bio goes here"
            "photo": raw photo data
            "artist": [00001, 00003, 00005]
        }

## Release ID [/release/{release_id}]
    + release_id (number) - ID of the release in the form of an integer

### View Release Info by ID [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "1989"
            "artist": [00001]
        }
        
## Release Name [/release/{release_name}]
    + release_name (string) - Name of the release in the form of a string (spaces must be underscores)

### View Release Info by Name [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "1989"
            "artist": [00001]
        }

## Concert ID [/concert/{concert_id}]
    + concert_id (number) - ID of the concert in the form of an integer

### View Concert Info by ID [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "1989 Tour"
            "location": "Austin"
            "date": "2015-07-04 13:00:00-00"
            "artist": [00001]
        }
        
## Concert Name [/concert/{concert_name}]
    + concert_name (string) - name of the concert in the form of a string (spaces must be underscores)

### View Concert Info by Name [GET]

+ Response 200 (application/json)

        {
            "id": 00001
            "name": "1989 Tour"
            "location": "Austin"
            "date": "2015-07-04 13:00:00-00"
            "artist": [00001]
        }

